### ISSUE TITLE
Future for OSX platform?

### ISSUE THREAD

**Issue by jayloofah** [CHEF-KOCH/Spotify-Ad-free#13]
There are alternatives for Windows (a fork of BlockTheSpot is still quite active), however I was wondering if there were any similar methods of blocking that wouldn't require a hosts file for OSX? I know one solution is downgrading (< 1.0.80) and using a fairly simple list - it seems to be the best alternative at this point.

**Comment by CHEF-KOCH** [comment]
Hey,
did you read the readme? [MacOS is mentioned](https://github.com/CHEF-KOCH/Spotify-Ad-free#macos), since I do not test MacOS you could report back if the project still works (_I doubt it_).

**Comment by jayloofah** [comment]
Using the most recent block list at https://raw.githubusercontent.com/CHEF-KOCH/Spotify-Ad-free/master/filter/Spotify-HOSTS.txt, the bottom banner still appears and there seem to be some issues will loading album art. But the banner issue can be resolved by downgrading. The primary culprit is spclient.wg.spotify.com.

**Comment by CHEF-KOCH** [comment]
## As for MacOS
You could use Spotify PWA (Progressive Web App) (Chrome/Firefox) with a [Media Controls extension](https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen/r). There are no ads because the web player version still can be ad-blocked. 

## About HOSTS, Spotify etc
* The banner is not removable anymore since one year, it's hardcoded now within the client. I guess is started with 1.1.5+ (stable) it was already added in higher 1.14 version (beta ones). Which means I need to modify the client itself.
* I talked about how efficient HOSTS blocking is over [here](https://github.com/CHEF-KOCH/Spotify-Ad-free/issues/12). There is also a "blocking" protection, even if you manage to block all ads (audio and video) you will whenever a new song is been played and no cached, stop hearing anything and you need to restart the player. The minimum I figured out which does not break is 2 audio ads in 2 hours, that said I need to release something which is closed source so that Spotify can't respond on it. 
* I corrected the readme.md with the latest information regarding MacOS.

**Comment by CHEF-KOCH** [comment]
@jayloofah You tried Spotify-adblock-macos ? Can you report back. THX.

**Comment by jayloofah** [comment]
Testing right now - will report back.

**Comment by CHEF-KOCH** [comment]
> I'm not sure if this method is sustainable in the long run. 

Whitelistening is always better than less blacklistening and causes less effort. It's unlikely that Spotify changes legitimate domains, what they can do is to deliver audio and video and audio ads via those whitelisted domains but this is in general a "game over".

**Comment by P0SlX** [comment]
> ## About MacOS
> You could use Spotify PWA ([Progressive Web App](https://en.wikipedia.org/wiki/Progressive_web_application)) (Chrome/Firefox) with a [Media Controls extension](https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen/r). There are no ads because the web player version still can be ad-blocked.
> 
> ## Still maintained "ad-blocker" solution for MacOS
> * [Spotify-adblock-macos](https://github.com/AnanthVivekanand/spotify-adblock-macos) - **I need confirmation if it works or not.** If yes, this method can be adopted for Windows and Linux as well. It seems most effective since Spotify will not likely remove the proxy function.
> 
> ## About HOSTS, Spotify etc
> * The banner is not removable anymore since one year, it's hardcoded now within the client. I guess is started with 1.1.5+ (stable) it was already added in higher 1.14 version (beta ones). Which means I need to modify the client itself.
> * I talked about how efficient HOSTS blocking is over [here](https://github.com/CHEF-KOCH/Spotify-Ad-free/issues/12). There is also a "blocking" protection, even if you manage to block all ads (audio and video) you will whenever a new song is been played and not cached, stop hearing anything and you need to restart the player. The minimum I figured out which does not break is 2 audio ads in 2 hours, that said I need to release something which is closed source so that Spotify can't respond on it.
> * I corrected the readme.md with the latest information regarding MacOS.

It works on 10.15.3 perfectly, I also forked the project and made an app with a script in it to run the proxy in background launch Spotify as well

**Comment by mgoyanes** [comment]
I know that this is closed but using the latest version provided here (Spotify 1.1.36.734.g8731c306) and using the HOSTS file provided here, ads are still playing.

Used the latest version of https://github.com/AnanthVivekanand/spotify-adblock-macos and after a while, Spotify simply mutes. No more music.

I did both these tests using my local IP (EU country) and a VPN pointing to USA 

Using MacOs 10.15.5.

**Comment by CHEF-KOCH** [comment]
Do not push [already reported issues](https://github.com/AnanthVivekanand/spotify-adblock-macos/issues/12) into my repository in the hope I solve other people's problems.

We have a whiteliste and it's from what I can say complete.
